### ISSUE TITLE
execo_engine

### ISSUE THREAD

**Issue by Kjaouen** [lpouillo/boxmodel#5]
Salut !
J ai un probleme tout bete. je lance les commandes dans mon terminal et il ne peut pas faire tourner les programmes parce qu il ne trouve pas le module execo engine alors que j ai installe execo et copie le fichier execo engine dans boxmodel, avec et sans extensions.
voila l erreur : 
klervia@klervia-laptop:~/boxmodel$ execo-run ZnDietRatio -ML
Traceback (most recent call last):
  File "/usr/local/bin/execo-run", line 48, in <module>
    engine_module = __import__(module_name)
  File "./ZnDietRatio.py", line 2, in <module>
    from IsotopicBoxModel import *
  File "./IsotopicBoxModel.py", line 16, in <module>
    from execo_engine import Engine, ParamSweeper, sweep, slugify, logger
ImportError: No module named execo_engine
klervia@klervia-laptop:~/boxmodel$ 

Merci !!!

**Comment by lpouillo** [comment]
Fixed
