### ISSUE TITLE
Format des figures

### ISSUE THREAD

**Issue by Kjaouen** [lpouillo/boxmodel#7]
Est il possible d"exporter les figures evolution sous format pdf ou ps ?

**Comment by lpouillo** [comment]
Oui. Tu remplaces evolution.png => evolution.pdf. 
Mais ce n'est pas une manière propre car cela devrait être un paramètre en fait.

Sinon a posteriori
http://doc.ubuntu-fr.org/imagemagick#convert

**Comment by Kjaouen** [comment]
merci !
